@set allusersprofile=c:\programdata
@set appdata=c:\users\minnullin_iz\appdata\roaming
@set commonprogramfiles=c:\program files\common files
@set commonprogramfiles(x86)=c:\program files (x86)\common files
@set commonprogramw6432=c:\program files\common files
@set computername=ws_p_minnullin
@set comspec=c:\windows\system32\cmd.exe
@set corona_sdk_path=c:\program files (x86)\corona labs\corona sdk\
@set devenvdir=c:\program files (x86)\microsoft visual studio 14.0\common7\ide\
@set facades_4.5=c:\program files (x86)\reference assemblies\microsoft\framework\.netframework\v4.5\facades
@set facades_4.5.1=c:\program files (x86)\reference assemblies\microsoft\framework\.netframework\v4.5.1\facades
@set facades_4.5.2=c:\program files (x86)\reference assemblies\microsoft\framework\.netframework\v4.5.2\facades
@set facades_4.6=c:\program files (x86)\reference assemblies\microsoft\framework\.netframework\v4.6\facades
@set facades_4.6.1=c:\program files (x86)\reference assemblies\microsoft\framework\.netframework\v4.6.1\facades
@set fps_browser_app_profile_string=internet explorer
@set fps_browser_user_profile_string=default
@set framework40version=v4.0
@set frameworkdir=c:\windows\microsoft.net\framework\
@set frameworkdir32=c:\windows\microsoft.net\framework\
@set frameworkversion=v4.0.30319
@set frameworkversion32=v4.0.30319
@set homedrive=c:
@set homepath=\users\minnullin_iz
@set include=c:\program files (x86)\microsoft visual studio 14.0\vc\include;c:\program files (x86)\microsoft visual studio 14.0\vc\atlmfc\include;c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt;c:\program files (x86)\windows kits\netfxsdk\4.6.1\include\um;c:\program files (x86)\windows kits\8.1\include\\shared;c:\program files (x86)\windows kits\8.1\include\\um;c:\program files (x86)\windows kits\8.1\include\\winrt
@set lib=c:\program files (x86)\microsoft visual studio 14.0\vc\lib;c:\program files (x86)\microsoft visual studio 14.0\vc\atlmfc\lib;c:\program files (x86)\windows kits\10\lib\10.0.10240.0\ucrt\x86;c:\program files (x86)\windows kits\netfxsdk\4.6.1\lib\um\x86;c:\program files (x86)\windows kits\8.1\lib\winv6.3\um\x86
@set libpath=c:\windows\microsoft.net\framework\v4.0.30319;c:\program files (x86)\microsoft visual studio 14.0\vc\lib;c:\program files (x86)\microsoft visual studio 14.0\vc\atlmfc\lib;c:\program files (x86)\windows kits\8.1\references\commonconfiguration\neutral;\microsoft.vclibs\14.0\references\commonconfiguration\neutral
@set localappdata=c:\users\minnullin_iz\appdata\local
@set logonserver=\\dc
@set moz_plugin_path=c:\program files (x86)\foxit software\foxit reader\plugins\
@set msbuildloadmicrosofttargetsreadonly=true
@set msbuildsdkspath=c:\program files (x86)\msbuild\sdks
@set msbuild_exe_path=c:\program files (x86)\pvs-studio\buildtools15\msbuild.exe
@set netfxsdkdir=c:\program files (x86)\windows kits\netfxsdk\4.6.1\
@set number_of_processors=8
@set onedrive=c:\users\minnullin_iz\onedrive
@set os=windows_nt
@set path=c:\program files (x86)\microsoft visual studio 14.0\common7\ide\commonextensions\microsoft\testwindow;c:\program files (x86)\msbuild\14.0\bin;c:\program files (x86)\microsoft visual studio 14.0\common7\ide\;c:\program files (x86)\microsoft visual studio 14.0\vc\bin;c:\program files (x86)\microsoft visual studio 14.0\common7\tools;c:\windows\microsoft.net\framework\v4.0.30319;c:\program files (x86)\microsoft visual studio 14.0\vc\vcpackages;c:\program files (x86)\html help workshop;c:\program files (x86)\microsoft visual studio 14.0\team tools\performance tools;c:\program files (x86)\windows kits\8.1\bin\x86;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\;c:\program files (x86)\microsoft visual studio 14.0\common7\ide\commonextensions\microsoft\teamfoundation\team explorer\nativebinaries\x86;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files (x86)\nvidia corporation\physx\common;c:\program files\tortoisesvn\bin;c:\program files (x86)\windows kits\8.1\windows performance toolkit\;c:\program files\microsoft sql server\120\tools\binn\;c:\program files\git\cmd;c:\program files\tortoisegit\bin;c:\users\minnullin_iz\appdata\local\programs\python\python36-32\scripts\;c:\users\minnullin_iz\appdata\local\programs\python\python36-32\;c:\users\minnullin_iz\appdata\local\programs\python\launcher\;c:\users\minnullin_iz\appdata\local\microsoft\windowsapps
@set pathext=.com;.exe;.bat;.cmd;.vbs;.vbe;.js;.jse;.wsf;.wsh;.msc
@set pkgdefapplicationconfigfile=c:\users\minnullin_iz\appdata\local\microsoft\visualstudio\14.0\devenv.exe.config
@set postgis_enable_outdb_rasters=1
@set postgis_gdal_enabled_drivers=gtiff png jpeg gif xyz dted usgsdem aaigrid
@set processor_architecture=amd64
@set processor_identifier=intel64 family 6 model 60 stepping 3, genuineintel
@set processor_level=6
@set processor_revision=3c03
@set programdata=c:\programdata
@set programfiles=c:\program files
@set programfiles(x86)=c:\program files (x86)
@set programw6432=c:\program files
@set prompt=$p$g
@set psmodulepath=c:\program files\windowspowershell\modules;c:\windows\system32\windowspowershell\v1.0\modules
@set public=c:\users\public
@set pvsbuildtoolsextensionspath=c:\program files (x86)\msbuild\
@set sessionname=console
@set systemdrive=c:
@set systemroot=c:\windows
@set temp=c:\users\minnul~1\appdata\local\temp
@set tmp=c:\users\minnul~1\appdata\local\temp
@set ucrtversion=10.0.10240.0
@set universalcrtsdkdir=c:\program files (x86)\windows kits\10\
@set userdnsdomain=prog.zarnitza.local
@set userdomain=prog
@set userdomain_roamingprofile=prog
@set username=minnullin_iz
@set userprofile=c:\users\minnullin_iz
@set vcinstalldir=c:\program files (x86)\microsoft visual studio 14.0\vc\
@set visualstudiodir=c:\users\minnullin_iz\documents\visual studio 2015
@set visualstudioedition=microsoft visual studio enterprise 2015
@set visualstudioversion=14.0
@set vs140comntools=c:\program files (x86)\microsoft visual studio 14.0\common7\tools\
@set vsinstalldir=c:\program files (x86)\microsoft visual studio 14.0\
@set vslang=1049
@set windir=c:\windows
@set windowslibpath=c:\program files (x86)\windows kits\8.1\references\commonconfiguration\neutral
@set windowssdkdir=c:\program files (x86)\windows kits\8.1\
@set windowssdklibversion=winv6.3\
@set windowssdkversion=\
@set windowssdk_executablepath_x64=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\x64\
@set windowssdk_executablepath_x86=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\

@call cl.exe